### ISSUE TITLE
About pasta

### ISSUE THREAD

**Issue by Karmem** [stevenaeola/progblack_2223#3] opened 2022-10-17 09:12 UTC
we need pictures of batman eating pastaaaa

**Comment by Nnxik** [comment] 2022-10-17 09:17
No spices

**Comment by Arya-Elfren** [comment] 2022-10-17 09:17
Duplicate of #9 and #7

**Comment by stevenaeola** [comment] 2022-10-17 09:17
Closed as duplicate

**Closed by stevenaeola** 2022-10-17 09:17 UTC
